server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/social_network_project?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
jwt:
  secret: orhgwejweogwoih32r899283r293r94goergnervnfpvmerjg90rjgerogn54094309tt4t934t34giermveiverv
